POST http://localhost:4000/api/persons/
content-type: application/json

{
    "name":"Leo", 
    "age":25,
    "status": "single"
}

###
DELETE http://localhost:4000/api/persons/5cad955900be31078cbc5f74

###
GET http://localhost:4000/api/persons/

###
PUT http://localhost:4000/api/persons/5cc482d8affb9537e0d276ff
content-type: application/json

{
    "status": "married"
}