POST http://localhost:4000/api/persons/
content-type: application/json

{
    "name":"Den", 
    "age":25,
    "status": "single"
}

###
DELETE http://localhost:4000/api/persons/5cad955900be31078cbc5f74

###
GET http://localhost:4000/api/persons/

###
PUT http://localhost:4000/api/persons/5cad95b300be31078cbc5f75
content-type: application/json

{
    "status": "married"
}